services:
  db:
    image: postgres:15-alpine
    container_name: boardgame_db
    environment:
      POSTGRES_DB: boardgames
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  auto-data:
    build: .
    depends_on:
      - db
    environment:
        PG_HOST: db
        PG_PORT: 5432
        PG_USER: user
        PG_PASSWORD: password
        PG_DB: boardgames
    volumes:
      - .:/app
    working_dir: /app
volumes: 
  postgres_data:
  